name: Create Notion diary page
on:
  push:
  schedule:
    - cron: '0 22 * * *'
jobs:
  create-notion-diary-page:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm run start
        env:
          TZ: 'Asia/Tokyo'
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
          NOTION_DIARY_DATABASE_ID: ${{ secrets.NOTION_DIARY_DATABASE_ID }}
